### ISSUE TITLE
Failed to activate the bracket-matcher-highlight package

### ISSUE THREAD

**Issue by jbernard1** [eerrecalde/bracket-matcher-highlight#7]
[Enter steps to reproduce:]

1. used the command line
2. ran atom . in the directory I wanted to open up.

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [bracket-matcher-highlight](https://github.com/eerrecalde/bracket-matcher-highlight) package 0.5.0

### Stack Trace

Failed to activate the bracket-matcher-highlight package

```
At Cannot find module '../build/Release/onig_scanner.node'

Error: Cannot find module '../build/Release/onig_scanner.node'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/bracket-matcher-highlight/node_modules/oniguruma/lib/oniguruma.js:4:17)
    at /packages/bracket-matcher-highlight/node_modules/oniguruma/lib/oniguruma.js:69:4)
    at /packages/bracket-matcher-highlight/node_modules/oniguruma/lib/oniguruma.js:71:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar.js:10:16)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar.js:365:4)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar.js:367:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar-registry.js:12:13)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar-registry.js:261:4)
    at /packages/bracket-matcher-highlight/node_modules/first-mate/lib/grammar-registry.js:263:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/src/compile-cache.js:239:29)
```

### Commands

```
     -0:16.2.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-bracket-highlight 0.3.2 
atom-jade 0.3.0 
atom-jinja2 0.6.0 
atom-material-syntax 1.0.6 
atom-material-ui 2.0.4 
atom-meteor-snippets 0.1.0 
atom-typescript 11.0.9 
autocomplete-meteor-packages 1.3.0 
bracket-matcher-highlight 0.5.0 
busy-signal 1.4.3 
cake-syntax 1.0.2 
css-color-name 0.4.0 
daylight-ui 0.2.2 
docblockr 0.11.0 
emmet 2.4.3 
es6-javascript 1.0.0 
file-icons 2.1.11 
fizzy 0.21.0 
gruvbox 1.0.7 
indent-guide-improved 1.4.13 
intentions 1.1.5 
javascript-snippets 1.2.1 
language-aspx 0.5.0 
language-javascript-jsx 0.3.7 
language-lua 0.9.11 
language-stylus 0.2.0 
linter 2.2.0 
linter-lua 1.0.4 
linter-ui-default 1.6.10 
materialize-css 0.3.0 
meteor-api 2.20.0 
meteorjs-snippets-es6 1.3.0 
native-color-picker 0.2.5 
native-ui 0.23.0 
seti-syntax 1.1.3 
slime 2.1.0 
```

**Comment by eerrecalde** [comment]
Hey @jbernard1, do you know if the error was also before installing atom 1.21.1 update? 
I don't have issues with the current official version 1.20.1 x64.

Also, is this started failing after installing some other plugin?

**Comment by jbernard1** [comment]
@eerrecalde Sorry for the late response but I got this issue started after I upgraded yes.
